[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'none'; connect-src 'self';form-action 'self'; img-src 'self' https://piwik.technologiestiftung-berlin.de https://i.ytimg.com; base-uri 'self'; script-src 'self' https://piwik.technologiestiftung-berlin.de; style-src 'self'; font-src 'self'; manifest-src 'self'; object-src 'none'; frame-src youtube.com www.youtube.com www.youtube-nocookie.com;"
