name: Lighthouse

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-dist-dir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Lighthouse against a static dist dir
        uses: treosh/lighthouse-ci-action@v9
        with:
          # no urls needed, since it uses local folder to scan .html files
          build: npm run build
          start: npm start
          configPath: './lighthouserc.json'